# Installs

In [2]:
pip install -U sentence-transformers

     |████████████████████████████████| 81kB 3.6MB/s 
     |████████████████████████████████| 2.1MB 6.9MB/s 
     |████████████████████████████████| 1.2MB 18.4MB/s 
     |████████████████████████████████| 870kB 40.3MB/s 
     |████████████████████████████████| 3.3MB 33.3MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-1.0.4-cp37-none-any.whl size=114307 sha256=71ce0ead8e289fcacd6b81d60fdac499304977e77f74b70f4dc7b101cea7523c
  Stored in directory: /root/.cache/pip/wheels/26/ea/89/d0d2e013d951b6d23270aa9ca4018b82632ab7cd933c331316
  Created wheel for sacremoses: filename=sacremoses-0.0.44-cp37-none-any.whl size=886084 sha256=0eac08bdd14db2f1b8b399a79763dd8f58c1feed73a63180ce7371816e5d9968
  Stored in directory: /root/.cache/pip/wheels/3e/fb/c0/13ab4d63d537658f448366744654323077c4d90069b6512f3c
Successfully built sentence-transformers sacremoses


In [3]:
pip install pdfminer.six

     |████████████████████████████████| 5.6MB 4.1MB/s 
     |████████████████████████████████| 3.2MB 35.6MB/s 


In [4]:
pip install transformers torch

In [5]:
pip install bert-extractive-summarizer

In [6]:
pip install sumy

     |████████████████████████████████| 92kB 3.2MB/s 
     |████████████████████████████████| 10.1MB 24.6MB/s 
  Created wheel for breadability: filename=breadability-0.1.20-py2.py3-none-any.whl size=21680 sha256=e65f017b674ced298f7ea32e383247b25b317b62c783e93afb94b08bfbeb7eab
  Stored in directory: /root/.cache/pip/wheels/5a/4d/a1/510b12c5e65e0b2b3ce539b2af66da0fc57571e528924f4a52
  Created wheel for pycountry: filename=pycountry-20.7.3-py2.py3-none-any.whl size=10746863 sha256=ecfb9a0686789ba94fa1e9cd50e940a80a49ab74bcddc8851d4ae0c87727ef79
  Stored in directory: /root/.cache/pip/wheels/33/4e/a6/be297e6b83567e537bed9df4a93f8590ec01c1acfbcd405348
Successfully built breadability pycountry


In [7]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [8]:
pip install requests

In [9]:
pip install bs4

In [10]:
pip install PyPDF2

     |████████████████████████████████| 81kB 3.5MB/s 
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-cp37-none-any.whl size=61085 sha256=b57b57861fc05cad930b5810f8d41db2650859533f5b02c42ad8dd9e622fbc04
  Stored in directory: /root/.cache/pip/wheels/53/84/19/35bc977c8bf5f0c23a8a011aa958acd4da4bbd7a229315c1b7
Successfully built PyPDF2


In [11]:
pip install newspaper3k

     |████████████████████████████████| 215kB 4.4MB/s 
     |████████████████████████████████| 92kB 5.1MB/s 
     |████████████████████████████████| 81kB 5.3MB/s 
     |████████████████████████████████| 7.4MB 10.6MB/s 
  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-cp37-none-any.whl size=13538 sha256=30b4a303249b8e4bd1b63738e1cd358a0ae0749514a49661f3c8ba8f69868a8a
  Stored in directory: /root/.cache/pip/wheels/81/2b/43/a02ede72324dd40cdd7ca53aad718c7710628e91b8b0dc0f02
  Created wheel for jieba3k: filename=jieba3k-0.35.1-cp37-none-any.whl size=7398406 sha256=cc0934733a8330771e484def9585c3688fbda895005effffc61f24831687d70f
  Stored in directory: /root/.cache/pip/wheels/83/15/9c/a3f1f67e7f7181170ad37d32e503c35da20627c013f438ed34
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-cp37-none-any.whl size=3358 sha256=8aaff3583fc130ddd7aae497e6a7bd3a15c4b55a37d4b89276643cab1558bb33
  Stored in directory: /root/.cache/pip/wheels/de/03/ca/778e3a7a627e3d98836cc890e7cb40c7

# Libraries

In [12]:
from nltk.cluster.util import cosine_distance
import pandas as pd
import numpy as np
import networkx as nx
from nltk.tokenize import sent_tokenize
from sentence_transformers import SentenceTransformer
import requests
from bs4 import BeautifulSoup
import os
from os import listdir
from sumy.summarizers.lsa import LsaSummarizer

In [13]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer

In [14]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
import PyPDF2
from PyPDF2 import PdfFileReader
from pdfminer.high_level import extract_text
import newspaper 

In [15]:
import requests
#import RAKE
import operator
import timeit
import time
API_KEY = "AIzaSyAvZlAZHcE3lXigI2ZJxWQvCoCpF6qFiyY"
SEARCH_ENGINE_ID = "bf6585a79f0c6d8bb"

# Functions

In [16]:
def google_search(api_key, search_engine, query, page_number=1):
  start = (page_number - 1) * 10 + 1
  url = f"https://www.googleapis.com/customsearch/v1?key={api_key}&cx={search_engine}&q={query}&start={start}"
  data = requests.get(url).json()
  return data

In [17]:
def results(data):
  search_items = data.get("items")
  for i, search_item in enumerate(search_items, start=1):
    title = search_item.get("title")
    snippet = search_item.get("snippet")
    link = search_item.get("link")
    print("Title:", title)
    print("Description:", snippet)
    print("URL:", link, "\n")


In [18]:
def only_link(data):
  search_items = data.get("items")
  link=[]
  for i, search_item in enumerate(search_items, start=1):
    link.append(search_item.get("link")) 
    #print("URL:", link, "\n")
  return  link

In [19]:
def Sort (info):
  info.sort(key = lambda x: x[1], reverse=True)
  return info

In [20]:
def read_file(files):
  myfile = open(files, "r")
  readfiles=myfile.readlines()
  text =""
  for line in range(len(readfiles)):
    text = text + " "+ readfiles[line]
  return text 

In [21]:
#building the similarity matrix
def sim_matrix(sentences, stop_words):
    length =len(sentences)
    sim_mat = np.zeros((length, length))
    for sen1 in range(length):
        for sen2 in range(length):
    # Create an empty similarity matrix
            if sen1 == sen2: 
                continue 
            sim_mat[sen1][sen2] = sentence_similarity(sentences[sen1], sentences[sen2], stop_words)

    return sim_mat

In [22]:
def sentence_similarity(sent1, sent2, stopwords=None):
    if stopwords is None:
        stopwords = []
 
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
 
    # build the vector for the first sentence
    for w in sent1:
        if w in stopwords:
            continue
        vector1[all_words.index(w)] += 1
 
    # build the vector for the second sentence
    for w in sent2:
        if w in stopwords:
            continue
        vector2[all_words.index(w)] += 1
 
    return 1 - cosine_distance(vector1, vector2)

In [23]:
def generate_summary(sentences,stop_words,top_n=5):
    summarize_text = []
    summarized_text =""
    sentence_similarity_martix = sim_matrix(sentences, stop_words)

    sentence_similarity_graph = nx.from_numpy_array(sentence_similarity_martix)
    scores = nx.pagerank(sentence_similarity_graph)
    print(sentence_similarity_graph)
    ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
   # print("Indexes of top ranked_sentence order are ", ranked_sentence)    

    for i in range(top_n):
      summarized_text= summarized_text +" "+ ranked_sentence[i][1]

    return summarized_text

# Actual Using LSA Summarizer

In [1]:
!mkdir new_folder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [24]:
textatten = read_file("/content/Project_info/kkkk.txt")
sentencesAtten=sent_tokenize(textatten)

In [25]:
#Read all the txt files in my folder 
all_text=[]
database = " "
from os.path import isfile, join
onlyfiles = [f for f in listdir('/content/Project_info') if isfile(join("/content/Project_info", f))]
for i in range(len(onlyfiles)):
    textatten = read_file('/content/Project_info'+ '/' + onlyfiles[i])
    database = database+ " " +textatten
    all_text.append(textatten)

In [ ]:
print(onlyfiles)

['Arist.txt', 'Structural_bio.txt', 'jjlaw.txt', 'Neural.txt', 'webscraper.txt', 'SmartStoplist.txt', 'Attention.txt', 'kkkk.txt', 'shakesphere.txt', 'educational development.txt', 'nuclear.txt', 'TwoStage.txt', 'morals.txt', 'music.txt', 'Evolution.txt', 'humSym.txt', 'climate.txt', 'canal.txt', 'moralsandethics.txt', 'earth.txt', 'fullmoon.txt']


In [26]:
print(len(onlyfiles))

20


# User Requirement 3 -- Finding Similar Document

In [ ]:
parser = PlaintextParser.from_string(textatten,Tokenizer("english"))
summarizer_lsa = LsaSummarizer()
# Summarize using sumy LSA
summary =summarizer_lsa(parser.document,2)
lsa_summary=""
for sentence in summary:
    lsa_summary+=str(sentence)  
print(lsa_summary)

For high similarity values, the overlap is much bigger than expected by chance as in 10 random permutation cases.Full size image Shared symptoms indicate shared genes between diseases We integrated three genotype–phenotype databases, yielding 28,336 disease–gene associations (Supplementary Methods, Supplementary Data 6) and constructed a Human Disease Network as described in Goh et al.13, in which two diseases are connected if they share an associated gene.


In [ ]:
#myquery= input("Please enter the information to be searched ")
data =google_search(API_KEY,SEARCH_ENGINE_ID,lsa_summary)
results(data)
#print(data)

Title: Human symptoms–disease network | Nature Communications
Description: Jun 26, 2014 ... Here, Zhou et al.link diseases via their symptom overlap, and show that similar ... 
Full size image ... For high similarity values, the overlap is much bigger than 
expected by ... Shared symptoms indicate shared genes between diseases. We 
integrated three genotype–phenotype databases, yielding 28,336 ...
URL: https://www.nature.com/articles/ncomms5212 

Title: (PDF) Human symptoms–disease network
Description: Jun 26, 2014 ... For high similarity values, the overlap is much bigger than expected by chance as 
in 10 ... Random expectation is derived from 10 random permutations, error bars 
denote s.d. (b) ... Shared symptoms indicate shared genes between diseases. 
We integrated three genotype–phenotype databases, yielding.
URL: https://www.researchgate.net/publication/263430196_Human_symptoms-disease_network 

Title: the 2 of 3 and 4 0 5 to 6 a 7 in 8 1 9 for 10 image 11 2 12 is 13 3 14 ...
Des

With Generate Summ Function

In [ ]:
summarised =generate_summary(sentencesAtten,'SmartStoplist.txt' ,3)
print(summarised)


 Performance of several techniques has been already reported on this set, including N-gram models, LSA-based model [32], log-bilinear model [24] and a combination of recurrent neural networks that currently holds the state of the art performance of 55.4% accuracy on this benchmark [19]. However, several practical solutions were proposed for avoiding it; either using hierarchical versions of the softmax [25, 23, 18], or avoiding normalized models completely by using models that are not normalized during training [4, 9]. The new architectures directly follow those proposed in our earlier work [13, 14], where it was found that neural network language model can be successfully trained in two steps: first, continuous word vectors are learned using simple model, and then the N-gram NNLM is trained on top of these distributed representations of words.


In [ ]:
data =google_search(API_KEY,SEARCH_ENGINE_ID,summarised)
results(data)

Title: Efficient Estimation of Word Representations in Vector Space
Description: Sep 7, 2013 ... Furthermore, we show that these vectors provide state-of-the-art perfor- ... 
However, the simple techniques are at their limits in many tasks. ... Recurrent 
neural network based language model has been ... been already reported on this 
set, including N-gram models, LSA-based model [32], log-bilinear model ...
URL: https://arxiv.org/pdf/1301.3781 

Title: (PDF) Efficient Estimation of Word Representations in Vector Space
Description: Oct 21, 2014 ... Many current NLP systems and techniques treat words as atomic units ... 
Recurrent neural network based language model has been proposed to ... been 
already reported on this set, including N-gram models, LSA-based model [32], 
log-bilinear ... performance of 55.4% accuracy on this benchmark [19].
URL: https://www.researchgate.net/publication/234131319_Efficient_Estimation_of_Word_Representations_in_Vector_Space 

Title: Representation and Tr

# WebStripping 

In [ ]:
URL_link =only_link(data)
Extracted_pdf =[]
length=0
if len(URL_link)>2:
  length =2
else:
  length = len(URL_link)
for i in range(length):
  if URL_link[i].find("pdf")!=-1:
    response = requests.get(URL_link[i]) 
    pdf = open("pdf"+str(i)+".pdf", 'wb') 
    pdf.write(response.content) 
    pdf.close() 
    print("File ", i, " downloaded")
    text = extract_text("pdf"+str(i)+".pdf")
 
    #print(text)
    Extracted_pdf.append(text)
  
  else:
    try:
      Url_i = newspaper.Article(url="%s" % (URL_link[i]), language='en') 
      Url_i.download() 
      Url_i.parse() 
      Extracted_pdf.append(Url_i.text)
      print('Successful')
    except:
      print('something went wrong')

File  0  downloaded
Successful


In [ ]:
sentencesweb=sent_tokenize(text)
sentencesAtten=sent_tokenize(textatten)

# Document Similarity

In [ ]:
#TRying without stripping
Extracted_pdf=all_text


In [ ]:
Tokenized_Stripped=[]
for i in range(len(Extracted_pdf)):
  sentenceh=sent_tokenize(Extracted_pdf[i])
  Tokenized_Stripped.append(sentenceh)


In [ ]:
sentencesweb=sent_tokenize(text)
sentencesAtten=sent_tokenize(textatten)
model = SentenceTransformer('bert-base-nli-mean-tokens')
text_embeddings = model.encode(sentencesweb, batch_size = 8, show_progress_bar = True)
text_embeddings2 = model.encode(sentencesAtten, batch_size = 8, show_progress_bar = True)
np.shape(text_embeddings)

NameError: ignored

# Trial 2

In [ ]:
#Tokenizing the received
textevol = read_file("Evolution.txt")
sentencesevol=sent_tokenize(textevol)
textStruct = read_file("Structural_bio.txt")
sentencesStruct=sent_tokenize(textStruct)

In [ ]:
parser = PlaintextParser.from_string(textStruct,Tokenizer("english"))
summarizer_lsa = LsaSummarizer()
# Summarize using sumy LSA
summary =summarizer_lsa(parser.document,2)
lsa_summary=""
for sentence in summary:
    lsa_summary+=str(sentencesStruct)  
print(lsa_summary)

[' Structural bioinformatics\n CLoNe: automated clustering based on local density\n neighborhoods for application to biomolecular structural\n ensembles\n Sylvain Tra¨ ger1,2, Giorgio Tamo` 1,2, Deniz Aydin1,2, Giulia Fonti1,2,\n Martina Audagnotto1,2 and Matteo Dal Peraro1,2,*\n 1\n Institute of Bioengineering, School of Life Sciences, Ecole Polytechnique Fe´ de´ rale de Lausanne, Lausanne 1025, Switzerland and 2\n Swiss Institute of Bioinformatics, Lausanne 1015, Switzerland\n *To whom correspondence should be addressed.', 'Associate Editor: Lenore Cowen\n Received on January 8, 2020; revised on July 14, 2020; editorial decision on August 12, 2020; accepted on August 18, 2020\n Abstract\n Motivation: Proteins are intrinsically dynamic entities.', 'Flexibility sampling methods, such as molecular dynamics or\n those arising from integrative modeling strategies, are now commonplace and enable the study of molecular conformational landscapes in many contexts.', 'Resulting structural ense

In [ ]:
lsa_summary[0]

'['

In [ ]:
myquery= input("Please enter the information to be searched ")
data =google_search(API_KEY,SEARCH_ENGINE_ID,myquery)
results(data)

Please enter the information to be searched Structural bioinformatics\\n CLoNe: automated clustering based on local density\\n neighborhoods for application to biomolecular structural\\n ensembles\\n Sylvain Tra¨ ger1,2, Giorgio Tamo` 1,2, Deniz Aydin1,2, Giulia Fonti1,2,\\n Martina Audagnotto1,2 and Matteo Dal Peraro1,2,*\\n 1\\n Institute of Bioengineering, School of Life Sciences, Ecole Polytechnique Fe´ de´ rale de Lausanne, Lausanne 1025, Switzerland and 2\\n Swiss Institute of Bioinformatics, Lausanne 1015, Switzerland\\n *To whom correspondence should be addressed.', 'Associate Editor: Lenore Cowen\\n Received on January 8, 2020; revised on July 14, 2020; editorial decision on August 12, 2020; accepted on August 18, 2020\\n Abstract\\n Motivation: Proteins are intrinsically dynamic entities.', 'Flexibility sampling methods, such as molecular dynamics or\\n those arising from integrative modeling strategies, are now commonplace and enable the study of molecular conformational lan

In [ ]:
url = "https://academic.oup.com/bioinformatics/advance-article-pdf/doi/10.1093/bioinformatics/btaa742/36453399/btaa742.pdf  "

# Requests URL and get response object 
response = requests.get(url) 
i=1
pdf = open("pdf"+str(i)+".pdf", 'wb') 
pdf.write(response.content) 
pdf.close() 
print("File ", i, " downloaded")

File  1  downloaded


In [ ]:
import PyPDF2
from PyPDF2 import PdfFileReader
  
# creating a pdf file object
pdfFileObj = open('pdf1.pdf', 'rb')
  
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
with open("pdf1.pdf", 'rb') as f:
  pdf = PdfFileReader(f)
  information = pdf.getDocumentInfo()
  number_of_pages = pdf.getNumPages()

txt = f"""
Information about {"pdf1.pdf"}: 
Author: {information.author}
Creator: {information.creator}
Producer: {information.producer}
Subject: {information.subject}
Title: {information.title}
Number of pages: {number_of_pages}
    """

print(txt)

PdfReadError: ignored

In [ ]:
import newspaper 
URL_link =only_link(data)
all_scraped_documents =[]  
i= 0
# Parse through each url and display its content 
for url in URL_link: 
    print("First Run")
    url_i = newspaper.Article(url="%s" % (url), language='en') 
    url_i.download() 
    url_i.parse() 
    all_scraped_documents.append(url_i.text)
    i = i+1
    print(url_i.text)

First Run


ArticleException: ignored

In [ ]:
sentencesweb=sent_tokenize(textextract2)
text_embeddings = model.encode(sentencesweb, batch_size = 8, show_progress_bar = True)
text_embeddings2 = model.encode(sentencesAtten, batch_size = 8, show_progress_bar = True)
np.shape(text_embeddings)

In [ ]:
similarities = cosine_similarity(text_embeddings,text_embeddings2)
similarities_sorted = similarities.argsort()
# Get list of similarity indices i.e. doc at index 0 simialr with doc at index 1169 below.
id_1 = []
id_2 = []
score = []
for index,array in enumerate(similarities_sorted):
    id_1.append(index)
    id_2.append(array[-2])
    score.append(similarities[index][array[-2]])

In [ ]:
sum_of_sims =(np.sum(index_df["score"]))
print(sum_of_sims)
percentage_of_similarity = round(float((sum_of_sims / len(sentencesweb)) * 100))
print(f'Average similarity float: {float(sum_of_sims / len(sentencesweb))}')
print(f'Average similarity percentage: {float(sum_of_sims / len(sentencesweb)) * 100}')
print(f'Average similarity rounded percentage: {percentage_of_similarity}')

# User Requirement 2 - Document Similarity

In [28]:
#TRying without stripping
Extracted_pdf=all_text

In [29]:
Tokenized_Stripped=[]
for i in range(len(Extracted_pdf)):
  sentenceh=sent_tokenize(Extracted_pdf[i])
  Tokenized_Stripped.append(sentenceh)

In [ ]:
test="Transformers are emerging as a natural alternative to standard RNNs, replacing recurrent computations with a multi-head attention mechanism."

In [30]:
model = SentenceTransformer('bert-base-nli-mean-tokens')
main_embeddings = model.encode(database, batch_size = 8, show_progress_bar = True)
Atten_embeddings2 = model.encode(sentencesAtten, batch_size = 8, show_progress_bar = True)

In [ ]:
text_e = model.encode(test,batch_size = 8, show_progress_bar = True)

In [ ]:
np.shape(text_e)
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  sim=cosine_similarity(Atten_embeddings2,text_embeddings)
  print(sim)


[[0.500082   0.37137625 0.43623024 ... 0.48375675 0.51301897 0.4210522 ]
 [0.43521434 0.32533908 0.4915847  ... 0.41394514 0.4529869  0.4082212 ]
 [0.30836746 0.20715374 0.3453316  ... 0.16718225 0.17059006 0.23658954]
 ...
 [0.31313607 0.27396828 0.13552256 ... 0.23644742 0.22339532 0.25536156]
 [0.19243255 0.25778636 0.17841537 ... 0.05351097 0.06682938 0.12339282]
 [0.42192668 0.2856015  0.34474605 ... 0.52286506 0.524611   0.5303823 ]]



[[0.61137533 0.50334793 0.5590681  ... 0.42861474 0.24345231 0.47222167]
 [0.45038384 0.4287166  0.4421792  ... 0.35247698 0.26418757 0.3700279 ]
 [0.23704784 0.29900497 0.41122216 ... 0.3052108  0.31163636 0.19520469]
 ...
 [0.27419722 0.44222254 0.26739007 ... 0.42359257 0.55390227 0.3134383 ]
 [0.14815582 0.39179793 0.2673242  ... 0.54934907 0.6104392  0.35462427]
 [0.5270983  0.62573224 0.37934473 ... 0.4597299  0.2904395  0.583045  ]]



[[0.15631491 0.2916274  0.26209372 ... 0.15963207 0.33075154 0.42604643]
 [0.19273402 0.21589515 0.24303567 ... 0.17771704 0.3940194  0.48916054]
 [0.19363293 0.3185929  0.30358076 ... 0.32424128 0.31394568 0.42041332]
 ...
 [0.20943001 0.20123461 0.12726821 ... 0.21200489 0.12100569 0.41887018]
 [0.13336518 0.07131813 0.13223666 ... 0.20499173 0.02963325 0.51054984]
 [0.23140287 0.28301984 0.25958702 ... 0.1156558  0.27925384 0.45479345]]



[[0.74693376 0.30501166 0.60318756 ... 0.20884779 0.1890108  0.12758094]
 [0.6279459  0.32154363 0.63810754 ... 0.27824396 0.20466179 0.1976466 ]
 [0.4871789  0.29835606 0.33918685 ... 0.3222942  0.16744305 0.2814873 ]
 ...
 [0.36198753 0.15753242 0.34035432 ... 0.64401746 0.33237103 0.4940231 ]
 [0.29464406 0.0614459  0.29413536 ... 0.8913715  0.5434422  0.7036555 ]
 [0.5608275  0.37651646 0.5703299  ... 0.32603148 0.2975809  0.257293  ]]



[[ 0.5703893   0.5502107   0.5222447  ...  0.45870775  0.56089914
   0.5272311 ]
 [ 0.34735402  0.5704192   0.39986932 ...  0.4005938   0.4987712
   0.32518184]
 [ 0.3230586   0.32606912  0.35745755 ...  0.16503555  0.3059482
   0.11574011]
 ...
 [ 0.17069472  0.24584907  0.0994084  ...  0.19359006  0.06878863
   0.11075881]
 [ 0.11962534  0.25234166  0.06101007 ...  0.15261184 -0.049052
  -0.02635994]
 [ 0.34372786  0.52186     0.30751246 ...  0.42192015  0.47240978
   0.38509506]]



[[0.30147868 0.42076752]
 [0.30967113 0.38603702]
 [0.29868928 0.37897992]
 [0.3738618  0.40266055]
 [0.25042152 0.27862427]
 [0.50158215 0.6028894 ]
 [0.22105171 0.42584574]
 [0.2773854  0.36848688]
 [0.3308535  0.5035879 ]
 [0.28293017 0.48389632]
 [0.41432077 0.46949372]
 [0.34601006 0.53513294]
 [0.19031177 0.42627856]
 [0.2920627  0.33226433]
 [0.4072497  0.4935918 ]
 [0.20781189 0.27407795]
 [0.3863298  0.49765062]
 [0.2950101  0.3955552 ]
 [0.30840528 0.4105847 ]
 [0.3015904  0.42029142]
 [0.3854751  0.43235278]
 [0.27592814 0.34117606]
 [0.1562147  0.26243696]
 [0.33932185 0.33755675]
 [0.4122565  0.44028354]
 [0.2241741  0.32927135]
 [0.11085898 0.17661384]
 [0.4011365  0.41191012]
 [0.40191308 0.32110673]
 [0.5270103  0.60566306]
 [0.4005357  0.3472808 ]
 [0.24105385 0.3099594 ]
 [0.34609485 0.32577607]
 [0.288025   0.5284877 ]
 [0.3262248  0.28684622]
 [0.26415074 0.52423143]
 [0.28547272 0.3292008 ]
 [0.3068209  0.37508962]
 [0.38739127 0.4038063 ]
 [0.35162747 0.36189982]


[[0.7000258  0.25175643 0.57554555 ... 0.56370413 0.27188924 0.30383176]
 [0.5435044  0.27610645 0.5950813  ... 0.41072428 0.30852178 0.28528956]
 [0.29952127 0.3375562  0.5257551  ... 0.24047299 0.30406722 0.28036958]
 ...
 [0.40879452 0.28122458 0.3495885  ... 0.50193703 0.48155686 0.55946404]
 [0.22583738 0.22314231 0.32141396 ... 0.34912905 0.6140795  0.6524327 ]
 [0.5765953  0.33166254 0.4852774  ... 0.5397999  0.4408275  0.32843015]]



[[0.99999994 0.5643122  0.42146313 ... 0.35663822 0.19377151 0.6031613 ]
 [0.5643122  1.         0.54403406 ... 0.33779398 0.27794272 0.5956769 ]
 [0.42146313 0.54403406 0.99999994 ... 0.35586116 0.29006428 0.27631056]
 ...
 [0.35663822 0.33779398 0.35586116 ... 1.         0.6930569  0.45465696]
 [0.19377151 0.27794272 0.29006428 ... 0.6930569  1.0000002  0.31996465]
 [0.6031613  0.5956769  0.27631056 ... 0.45465696 0.31996465 1.        ]]



[[0.20314808 0.52950436 0.23681116 ... 0.20287299 0.14842933 0.2345312 ]
 [0.3269737  0.36506906 0.33224243 ... 0.18705529 0.19373934 0.37201053]
 [0.36022592 0.21460676 0.29678106 ... 0.11741532 0.22918457 0.46279496]
 ...
 [0.18188597 0.19745891 0.16420658 ... 0.18013671 0.32469976 0.23705098]
 [0.13351652 0.16329889 0.07424352 ... 0.13987209 0.34142506 0.3137954 ]
 [0.20846887 0.38446215 0.26811472 ... 0.16877255 0.27995276 0.30418497]]



[[0.48046216 0.6569991  0.59196687 ... 0.2848539  0.13712686 0.17608897]
 [0.35636654 0.47025284 0.5479683  ... 0.17382987 0.24156302 0.26689398]
 [0.25013483 0.3285131  0.54082775 ... 0.14705056 0.2774175  0.2946241 ]
 ...
 [0.42673644 0.25062943 0.24766234 ... 0.3068365  0.6581074  0.5774404 ]
 [0.38996112 0.14694208 0.22910783 ... 0.33595836 0.87235254 0.73879534]
 [0.6071885  0.56130946 0.39151466 ... 0.33863002 0.25371242 0.24261908]]



[[ 0.4357509   0.35750294  0.35750294 ...  0.5085038   0.4361702
   0.21927139]
 [ 0.23787509  0.17251672  0.17251672 ...  0.43869266  0.29220486
   0.31784713]
 [ 0.07954857  0.02001773  0.02001773 ...  0.46268547  0.10526203
   0.22633691]
 ...
 [ 0.13085131  0.09647571  0.09647571 ...  0.33758473  0.16604508
   0.43679798]
 [-0.07920678 -0.13540348 -0.13540348 ...  0.21111092  0.06134531
   0.5203011 ]
 [ 0.421114    0.30615497  0.30615497 ...  0.39762586  0.41932243
   0.39921835]]



[[0.5799029  0.5029831  0.3758227  ... 0.4874066  0.47759646 0.5185939 ]
 [0.55622494 0.5855359  0.4906707  ... 0.42912412 0.3550076  0.3153553 ]
 [0.33703426 0.32475674 0.30479154 ... 0.32460824 0.18570848 0.20663148]
 ...
 [0.52517575 0.3767743  0.31544396 ... 0.3588543  0.27817824 0.17148176]
 [0.46480206 0.3906929  0.32494184 ... 0.26736295 0.24026853 0.11633448]
 [0.56958544 0.4913786  0.41463405 ... 0.54539305 0.46031046 0.35038462]]



[[0.320257   0.30321014 0.33575374 ... 0.3739255  0.3945546  0.20164135]
 [0.58176816 0.46108973 0.523667   ... 0.33414662 0.42587346 0.33888644]
 [0.4694257  0.35988754 0.3817956  ... 0.38451612 0.42211813 0.43636572]
 ...
 [0.25739634 0.24442771 0.36991686 ... 0.26964855 0.1839649  0.44626048]
 [0.31907168 0.3031207  0.4158075  ... 0.11354114 0.19433123 0.64353144]
 [0.3228001  0.3806596  0.38858795 ... 0.3506524  0.29391393 0.18944724]]



[[ 0.4065157   0.18641661  0.31957227 ...  0.24979557  0.20441645
   0.54798615]
 [ 0.50666296  0.23664361  0.28363517 ...  0.23030603  0.22641718
   0.4244727 ]
 [ 0.3816795   0.290068    0.05635658 ...  0.30159178  0.3726245
   0.32015407]
 ...
 [ 0.22197446  0.62305725  0.04432455 ...  0.5204027   0.48501956
   0.31777018]
 [ 0.03307178  0.7076414  -0.11871515 ...  0.5796965   0.53848386
   0.24260394]
 [ 0.34540302  0.2582715   0.2926215  ...  0.31332195  0.25013423
   0.47624877]]



[[0.49401164 0.5733899  0.43813682 ... 0.27321234 0.2042114  0.541095  ]
 [0.37603486 0.43030697 0.3515916  ... 0.25557637 0.26916015 0.39580125]
 [0.17279133 0.22890833 0.18090366 ... 0.27691    0.25248036 0.40693563]
 ...
 [0.3467394  0.28083146 0.31574774 ... 0.5374491  0.26554847 0.4086771 ]
 [0.11623822 0.19578208 0.28727928 ... 0.41664338 0.32976893 0.16385758]
 [0.49027044 0.5581601  0.54707086 ... 0.22063509 0.1571039  0.46266443]]



[[0.44791853 0.52992404 0.52712    ... 0.44136253 0.30219954 0.5216922 ]
 [0.43932545 0.42347902 0.5479612  ... 0.5130329  0.28646624 0.5267087 ]
 [0.21951012 0.11764923 0.37311995 ... 0.30976242 0.25936764 0.35776824]
 ...
 [0.15743555 0.2114597  0.2860391  ... 0.3945263  0.20126902 0.22517702]
 [0.0751894  0.10236627 0.19080989 ... 0.25825086 0.04425025 0.13548455]
 [0.5166145  0.5218513  0.38891113 ... 0.42989674 0.3394684  0.4006747 ]]



[[0.3446477  0.41253906 0.51902974 ... 0.5031823  0.43860075 0.30528343]
 [0.28954807 0.28328604 0.40213963 ... 0.413897   0.42861417 0.36527988]
 [0.3235809  0.28547895 0.27844262 ... 0.21484879 0.1628705  0.29708815]
 ...
 [0.24744079 0.12304424 0.1506857  ... 0.20260495 0.24340835 0.3118625 ]
 [0.18286037 0.01212342 0.03655304 ... 0.12258054 0.18123364 0.43290687]
 [0.329862   0.4432926  0.4978118  ... 0.53179014 0.46049452 0.39015174]]



[[ 0.37809393  0.37313095  0.37313095 ...  0.36622775  0.47529283
   0.3604402 ]
 [ 0.14556345  0.2197877   0.2197877  ...  0.24234149  0.29965833
   0.3069012 ]
 [ 0.11380924  0.07336435  0.07336435 ...  0.3536272   0.2597174
   0.07913011]
 ...
 [ 0.11209112  0.11719298  0.11719298 ... -0.04456037  0.14498582
   0.12054369]
 [-0.045155    0.13160118  0.13160118 ... -0.1509322   0.05517047
  -0.04277024]
 [ 0.3221979   0.34353027  0.34353027 ...  0.15286578  0.3212503
   0.42395347]]



[[0.29899824 0.3985516  0.41176403 ... 0.2340951  0.35093    0.35450178]
 [0.40140104 0.4449125  0.3792136  ... 0.42694792 0.429249   0.4034845 ]
 [0.24965411 0.37354222 0.1626504  ... 0.25402868 0.26978037 0.3680239 ]
 ...
 [0.20798123 0.18744934 0.37500644 ... 0.25302783 0.17430794 0.26426136]
 [0.20144305 0.24668822 0.4262635  ... 0.2778318  0.05828167 0.17175835]
 [0.40954417 0.30876157 0.39586937 ... 0.34395647 0.32895902 0.37362808]]



[[ 0.48850596  0.46132064  0.4874666  ...  0.44885564  0.35784537
   0.47670585]
 [ 0.27844465  0.28997934  0.4268472  ...  0.3062628   0.30220968
   0.36152282]
 [ 0.2792642   0.12293665  0.31036812 ...  0.30323315  0.24619398
   0.37577078]
 ...
 [ 0.20495284  0.11038713  0.261661   ...  0.10140549  0.12324471
   0.33538747]
 [ 0.00215467  0.02427682  0.11423587 ... -0.02647277  0.00815415
   0.19328988]
 [ 0.36163926  0.3854972   0.5000235  ...  0.25389975  0.4353888
   0.41998664]]



[[0.39678842 0.30233288 0.3819313  ... 0.3121314  0.43879563 0.3576962 ]
 [0.26575404 0.22383569 0.16308096 ... 0.18829912 0.315092   0.31985596]
 [0.1962134  0.2024474  0.22639637 ... 0.3314159  0.11784266 0.18780988]
 ...
 [0.08840225 0.18212524 0.11391152 ... 0.25227696 0.26437873 0.30199957]
 [0.01960891 0.27292132 0.05440545 ... 0.2870175  0.23275721 0.31172132]
 [0.3535366  0.30200797 0.25198263 ... 0.22921637 0.44455206 0.40634072]]


In [ ]:
np.sum(summ)/10778

0.2634891206334663

In [ ]:
 text_embeddingsAtt = model.encode(Tokenized_Stripped[6], batch_size = 8, show_progress_bar = True)

In [ ]:
cosine_similarity(text_e.reshape(1,-1),text_embeddingsAtt)

array([[0.56764644, 0.49769983, 0.9999999 , 0.66037214, 0.67782265,
        0.57601833, 0.363383  , 0.5618271 , 0.54577565, 0.53620666,
        0.2937849 , 0.5228121 , 0.54698396, 0.46937585, 0.3376271 ,
        0.6962118 , 0.6832021 , 0.4876876 , 0.35962626, 0.60703325,
        0.49555498, 0.2937849 , 0.62512624, 0.531629  , 0.37772298,
        0.66296047, 0.60611093, 0.6776063 , 0.53534055, 0.49375296,
        0.67673516, 0.74293214, 0.7403908 , 0.78523713, 0.66101   ,
        0.5669261 , 0.4115156 , 0.47162324, 0.46483123, 0.5983072 ,
        0.26239556, 0.5790606 , 0.57871634, 0.58304083, 0.63465965,
        0.3191596 , 0.4801163 , 0.6085659 , 0.36733362, 0.5431207 ,
        0.26702848, 0.47982973, 0.50061095, 0.2565706 , 0.2565706 ,
        0.39432934, 0.5457635 , 0.2185015 , 0.46731073, 0.44229442,
        0.37142915, 0.6453258 , 0.5144559 , 0.363191  , 0.47021323,
        0.467647  , 0.24626976, 0.47938403, 0.49323052, 0.6050861 ,
        0.5555667 , 0.53835595, 0.55388474, 0.45

In [ ]:
print(Tokenized_Stripped[6][2])

Transformers are emerging as a natural alternative to
 standard RNNs, replacing recurrent computations with a multi-head
 attention mechanism.


In [ ]:
print(text_embeddingsAtt[1])

[ 1.47825822e-01  1.08827245e+00  7.78244197e-01  6.04122765e-02
 -9.82216671e-02  7.08586648e-02  2.09459019e+00  4.97923255e-01
  3.92835051e-01  3.64855289e-01 -5.73243380e-01  6.03947282e-01
 -1.92880213e-01  7.83972204e-01  2.15592563e-01  2.80677527e-01
  8.04441497e-02 -7.40464807e-01 -2.59758025e-01 -2.66662925e-01
 -4.63076323e-01 -9.33516696e-02 -4.30731565e-01 -8.32081214e-02
  7.28107914e-02 -4.14863199e-01 -4.48254542e-03 -5.50534964e-01
 -1.16062331e+00  4.14513946e-01  3.89734767e-02  7.16293633e-01
  9.18357849e-01  1.56822458e-01  7.34586358e-01  6.60083055e-01
  6.51223958e-01 -3.71978372e-01 -2.64974553e-02 -5.21623254e-01
  1.04578280e+00 -8.67994949e-02  1.87289938e-01 -1.00704767e-01
 -9.34671164e-02  1.91160262e-01  1.51544678e+00 -9.87522602e-02
 -4.75678109e-02 -2.66307533e-01 -7.58429945e-01  1.66419521e-01
  1.11768639e+00  9.18708622e-01  2.33083546e-01 -6.04623914e-01
  5.07879615e-01 -1.50239563e+00  2.75308669e-01 -4.67427254e-01
 -3.31665784e-01 -7.47345

In [ ]:
print(text_e)

[-1.52057782e-01 -1.47779182e-01  1.59675169e+00  2.89795280e-01
  4.50343750e-02 -9.09184337e-01  3.79980765e-02 -4.99235779e-01
  4.54506248e-01 -5.68483472e-01  1.24772176e-01  1.32582343e+00
  1.09855957e-01  4.19149756e-01 -1.23701584e+00 -2.28308991e-01
 -9.17394698e-01 -1.11334920e+00 -8.06861222e-02  3.89250182e-02
 -3.96989770e-02 -1.36795491e-01 -2.92569757e-01  6.67948067e-01
 -1.84120715e-01  8.02432150e-02  6.46640897e-01 -4.62300450e-01
 -3.65363330e-01  3.49934965e-01 -1.66382685e-01  4.01627302e-01
  2.43796781e-02 -8.04337204e-01 -3.98705453e-01  1.06476796e+00
  3.69198054e-01 -4.55648214e-01  1.21473029e-01  3.52439463e-01
  4.04998839e-01 -3.10239851e-01 -1.93403840e-01  1.09715648e-01
 -1.47252560e+00  2.11378057e-02 -5.90250850e-01  5.70516288e-01
 -4.84679669e-01 -8.21989179e-01 -8.94890368e-01 -7.79922083e-02
 -4.17513311e-01  5.10202348e-02 -5.96515656e-01  9.15311649e-02
  8.45227003e-01 -1.26510680e+00 -2.19523877e-01 -4.13373053e-01
 -1.29822850e+00  8.56208

In [32]:
Tokenized_Stripped[9][8]

'Image 1 of 3\n Three nuclear submarines owned by Russia maneuvered to break through several feet of Arctic ice at the same time.'

In [33]:
Tokenized_Stripped[6][5]

'1\tIntroduction\n Many current NLP systems and techniques treat words as atomic units - there is no notion of similarity between words, as these are represented as indices in a vocabulary.'

In [34]:
Tokenized_Stripped[0][5]

'Finally, John Donne’s Holy Sonnet XII and Geoffrey Chaucer’s The Canterbury Tales impart decidedly anti-Semitic themes while alluding to the crucifixion of Jesus.'

In [36]:
#np.shape(text_e)
databasedict ={}
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  databasedict[onlyfiles[i]]=text_embeddings
  sumed =0
  #sim=cosine_similarity([text_e],text_embeddings)
  #print(sim)

trying

In [37]:
textCit = read_file("citation.txt")
sentencesCit=sent_tokenize(textCit)

In [38]:
text_embedCit = model.encode(textCit, batch_size = 8, show_progress_bar = True)

In [ ]:
onlyfiles

['Arist.txt',
 'Structural_bio.txt',
 'jjlaw.txt',
 'Neural.txt',
 'webscraper.txt',
 'SmartStoplist.txt',
 'Attention.txt',
 'kkkk.txt',
 'shakesphere.txt',
 'educational development.txt',
 'nuclear.txt',
 'TwoStage.txt',
 'morals.txt',
 'music.txt',
 'Evolution.txt',
 'humSym.txt',
 'climate.txt',
 'canal.txt',
 'moralsandethics.txt',
 'earth.txt',
 'fullmoon.txt']

In [42]:
for i in databasedict.values():
  #text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  #np.shape(text_embeddings)
  #databasedict[onlyfiles[i]]=text_embeddings
  #sumed =0
  print('/n')
  print('line')
  sim=cosine_similarity([text_embedCit],i)
  print(sim)

/n
line
[[0.50370926 0.40397125 0.19670874 0.5506997  0.4683129  0.648975
  0.52191114 0.5937376  0.58936936 0.5713487  0.4324297  0.61243916
  0.6334089  0.6147966  0.5407609  0.47724125 0.5589023  0.5547146
  0.62407595 0.5103978  0.45797956 0.549726   0.5930956  0.5893141
  0.5699271  0.58542824 0.47948346 0.61033535 0.49537006 0.49249765
  0.30806446 0.6138371  0.53133863 0.6125003  0.5441937  0.60635006
  0.5231694  0.46790817 0.5377828  0.36742553 0.4364132  0.53970736
  0.5945035  0.58948874 0.60267586 0.5119865  0.61743414 0.5279436
  0.6002577  0.5116699  0.50249666 0.54758584 0.4836046  0.5903432
  0.5957887  0.5430197  0.5320631  0.6023171  0.55864215 0.5216478
  0.64135647 0.68240166 0.6711173  0.45561123 0.5811584  0.47361246
  0.4813615  0.37413156 0.58290577 0.40604937 0.69486886 0.534399
  0.47115043 0.24880654]]
/n
line
[[ 0.43518692  0.4091164   0.17007177  0.23138095  0.10402798  0.32345933
   0.44480702  0.31308836  0.26577768  0.2776889   0.21547668  0.28148004
   

In [ ]:
print(sim)

[[0.5661872  0.3374996  0.574691   0.5319318  0.48343396 0.41211888
  0.5746923  0.54130924 0.44985303 0.2233786  0.11931786 0.2605713
  0.5227314  0.5227314  0.6190605  0.29164523 0.48830247 0.5597492
  0.5597492  0.5311677  0.44800344 0.4361654  0.27533764 0.43934232
  0.26153433 0.48419192 0.49470603 0.3864457  0.37201053 0.49238977
  0.35150623 0.3268925  0.28372613 0.18550992]]


In [ ]:
np.shape(text_e)
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  sim=cosine_similarity([text_e],text_embeddings)
  print(sim)


[[0.36714137 0.24988544 0.42904055 0.3059873  0.28943133 0.35502753
  0.33431083 0.32036346 0.34571916 0.19844237 0.4187257  0.26487684
  0.3118438  0.29268223 0.32937092 0.33769754 0.42029226 0.32107484
  0.29652694 0.28733617 0.36921552 0.30640352 0.30780262 0.25183335
  0.2360806  0.31511074 0.26112926 0.17748442 0.18685737 0.4334383
  0.44757012 0.26312304 0.3223739  0.33924    0.35390037 0.30811495
  0.2655289  0.35314947 0.32440546 0.25908726 0.35891408 0.35061085
  0.3702619  0.28343698 0.23077305 0.33681226 0.29485655 0.42071903
  0.3050876  0.18637145 0.24263684 0.3479171  0.2574744  0.17797908
  0.22673437 0.28767377 0.26381177 0.2536532  0.26860437 0.22487909
  0.26903784 0.3063487  0.35464793 0.3295655  0.23284882 0.23301639
  0.35060227 0.19222754 0.3650462  0.1789091  0.27381486 0.3611351
  0.35907066 0.33353347]]



[[0.5903007  0.504529   0.5377203  0.44715518 0.5291923  0.5404011
  0.44861913 0.6219251  0.5477716  0.6625265  0.49750596 0.61205995
  0.55881184 0.41943794 0.5918355  0.44778788 0.59443665 0.39625233
  0.588213   0.64042056 0.558395   0.32848406 0.370472   0.5335494
  0.48801962 0.5242419  0.53108925 0.4854672  0.5086949  0.47008508
  0.44060653 0.4762566  0.6564294  0.4439732  0.5886124  0.52258855
  0.7009886  0.5372212  0.5279285  0.3489464  0.5279571  0.59771585
  0.4501103  0.5438633  0.6422965  0.60957366 0.6483251  0.6609031
  0.4233765  0.50158775 0.5005916  0.5192363  0.3936336  0.5583699
  0.5441619  0.43891102 0.6185971  0.69686925 0.528134   0.61729383
  0.56994456 0.61117846 0.6143361  0.4989078  0.6182463  0.59725523
  0.31491232 0.534219   0.5577463  0.53631854 0.6255496  0.47425827
  0.49868572 0.59190035 0.5452993  0.44222105 0.49857786 0.49709538
  0.5964951  0.6263135  0.5699295  0.558105   0.5152477  0.27773428
  0.6913617  0.31540006 0.53749716 0.45980424 0.500


[[0.21960378 0.25817445 0.2258533  0.23115861 0.3444723  0.34731486
  0.45622635 0.31653678 0.36936086 0.5052813  0.39672738 0.40456542
  0.38400143 0.370557   0.36102158 0.41880733 0.35173714 0.37215555
  0.4210718  0.46364647 0.41343564 0.34772763 0.3633194  0.36314547
  0.48466814 0.45836258 0.40026942 0.27509853 0.23669264 0.3639387
  0.41330534 0.4096217  0.37839007 0.414121   0.380171   0.36239386
  0.4176433  0.3960873  0.37112975 0.45070457 0.37823007 0.35383654
  0.33444697 0.4142612  0.33692434 0.29787153 0.22965775 0.23932233
  0.373651   0.31369776 0.36655328 0.30552897 0.39858633 0.44149566
  0.329131   0.34323224 0.39831895 0.41298226 0.45209193 0.34454226
  0.3142659  0.39811546 0.4130672  0.51294845 0.3326462  0.21277383
  0.28298676 0.24776283 0.435349   0.31549346 0.23736045 0.4143692
  0.3658394  0.3498649  0.22562835 0.32573387 0.3357699  0.3789397
  0.40958762 0.37128675 0.35579067 0.420592   0.2588839  0.38335353
  0.4068309  0.239273   0.30872512 0.33048064 0.41


[[0.6676519  0.46006888 0.6711691  ... 0.3338415  0.23670843 0.27951866]]



[[0.33601028 0.5549336  0.4260399  0.48564947 0.43559986 0.45210567
  0.39089495 0.37463456 0.3147916  0.45031145 0.629987   0.45717475
  0.4819629  0.55799127 0.42889613 0.41381007 0.41833293 0.30034763
  0.4454882  0.45823848 0.32180235 0.38895726 0.6042785  0.45692676
  0.6159785  0.41830736 0.5630392  0.48881593 0.36662754 0.37056434
  0.42258072 0.48776704 0.53672576 0.34713873 0.34101123 0.4688464
  0.47234702 0.27128133 0.5475429  0.45873284 0.35064408 0.65703326
  0.44451717 0.4526386  0.43135497 0.5233031  0.5547612  0.5154487
  0.48343226 0.54109347 0.60154927 0.4495556  0.60996956 0.63158154
  0.49581563 0.5275259  0.5633674  0.43149048 0.44458726 0.44657138
  0.51513857 0.42927235 0.46738333 0.47305307 0.43238857 0.46670336
  0.48331428 0.40551496 0.4433377  0.5219723  0.46247077 0.39179277
  0.6268233  0.49784926 0.45109016 0.52400583 0.36795712 0.4257863
  0.45288453 0.46954396 0.3971396  0.51683843 0.46950388 0.5772114
  0.30729586 0.51863456 0.56229    0.60522556 0.494


[[0.42523792 0.49012545]]



[[0.56764644 0.49769983 0.9999999  0.66037214 0.67782265 0.57601833
  0.363383   0.5618271  0.54577565 0.53620666 0.2937849  0.5228121
  0.54698396 0.46937585 0.3376271  0.6962118  0.6832021  0.4876876
  0.35962626 0.60703325 0.49555498 0.2937849  0.62512624 0.531629
  0.37772298 0.66296047 0.60611093 0.6776063  0.53534055 0.49375296
  0.67673516 0.74293214 0.7403908  0.78523713 0.66101    0.5669261
  0.4115156  0.47162324 0.46483123 0.5983072  0.26239556 0.5790606
  0.57871634 0.58304083 0.63465965 0.3191596  0.4801163  0.6085659
  0.36733362 0.5431207  0.26702848 0.47982973 0.50061095 0.2565706
  0.2565706  0.39432934 0.5457635  0.2185015  0.46731073 0.44229442
  0.37142915 0.6453258  0.5144559  0.363191   0.47021323 0.467647
  0.24626976 0.47938403 0.49323052 0.6050861  0.5555667  0.53835595
  0.55388474 0.45560503 0.3638383  0.29129976 0.44432843 0.30229756
  0.5005586  0.4409786  0.5280671  0.64018965 0.45782965 0.5922707
  0.45470518 0.52684593 0.43851322 0.5416931  0.49160445 0


[[0.5755455  0.5950812  0.52575517 0.35450912 0.5992502  0.43075094
  0.6103653  0.53202987 0.41275746 0.36688066 0.3679907  0.5842122
  0.6006453  0.47305828 0.46082908 0.4248061  0.23935243 0.5488776
  0.5246948  0.55985796 0.5662104  0.750867   0.5628036  0.48048308
  0.32500377 0.6472881  0.28352648 0.60686004 0.6161987  0.575334
  0.65372676 0.5974932  0.57633805 0.42431834 0.4760686  0.49470297
  0.47702307 0.6254934  0.46867695 0.32177293 0.4658178  0.63187605
  0.40855974 0.48646942 0.5576786  0.4502737  0.38806036 0.28603595
  0.4813395  0.49394554 0.58427835 0.4719352  0.56230474 0.61290544
  0.57540464 0.37920672 0.58889556 0.7458321  0.3763137  0.5778764
  0.5763319  0.6353661  0.5938761  0.5381464  0.58399105 0.43400913
  0.7240727  0.5173015  0.7031214  0.70600927 0.5905702  0.45609066
  0.6303601  0.49318793 0.6023803  0.52739906 0.61792886 0.43145132
  0.4358828  0.6709397  0.5293056  0.59301686 0.48377243 0.44270664
  0.52975196 0.56896377 0.54215163 0.5419523  0.3906


[[0.34570003 0.39936668 0.39196715 0.24239278 0.20888503 0.31746018
  0.41335148 0.56454015 0.49058416 0.5148202  0.5454347  0.42157826
  0.43667793 0.5464212  0.5018274  0.4070675  0.14622167 0.44090074
  0.38148662 0.48431414 0.40459475 0.42707813 0.41027904 0.47143546
  0.3769944  0.4848148  0.54522145 0.2955801  0.5763406  0.39306575
  0.4912507  0.5079883  0.5454029  0.5703283  0.35110146 0.2527136
  0.5262821  0.39710832 0.1794251  0.32871658 0.15128002 0.39857823
  0.472623   0.28126335 0.21225803 0.13439399 0.25436088 0.13177219
  0.3871188  0.3941759  0.39253354 0.46652868 0.40311036 0.33118072
  0.47780305 0.44898272 0.48105073 0.4968447  0.2900492  0.49749976
  0.49583328 0.40349808 0.45904863 0.47947386 0.3441269  0.3612051
  0.39107108 0.4375218  0.41325372 0.32021785 0.49552488 0.3707047
  0.4775189  0.43127662 0.32608223 0.32594034 0.5295093  0.34875244
  0.3123822  0.4307567  0.47334704 0.44578582 0.3701205  0.334325
  0.48290622 0.4898036  0.48614025 0.51154304 0.4732


[[0.459187   0.47558278 0.60009265 0.3899666  0.5796629  0.5634383
  0.50804925 0.35647297 0.2937849  0.47503456 0.5424043  0.48908123
  0.55335635 0.46636945 0.295745   0.52987766 0.34105805 0.3973181
  0.31851992 0.41655058 0.5121157  0.31956422 0.44030046 0.38533774
  0.57773566 0.52115464 0.42777845 0.54893404 0.5415542  0.40910208
  0.5277102  0.51816875 0.37224472 0.34551862 0.5244396  0.33589882
  0.50848866 0.52209234 0.5968931  0.45290062 0.44906095 0.41747347
  0.5233783  0.48699695 0.23554614 0.49406412 0.443445   0.47454622
  0.5483329  0.69163567 0.3979137  0.5782019  0.26239556 0.4623649
  0.30321229 0.46214324 0.48450494 0.4093057  0.29593456 0.47804874
  0.47105056 0.41279438 0.48949882 0.5099114  0.33937678 0.4948085
  0.5342008  0.41700792 0.24355623 0.5511515  0.4434149  0.39303863
  0.5199316  0.41385055 0.38620925 0.5256805  0.32414538 0.2938099
  0.23087151 0.21077177 0.42868304 0.10383588 0.26443017 0.45145276
  0.28225315 0.51583254 0.35420674 0.53201205 0.4831


[[0.27772278 0.25726706 0.25726706 0.25708738 0.20159665 0.23380104
  0.23738739 0.20667087 0.25481135 0.25726706 0.2971094  0.25726706
  0.2971094  0.25726706 0.2749706  0.4147223  0.3502271  0.45876864
  0.4483183  0.33766073 0.31483465 0.30698788 0.23179895 0.33245048
  0.35154015 0.3399614  0.2998119  0.30308557 0.47495446 0.44492617
  0.4126633  0.44527578]]



[[0.6089654  0.5190939  0.63199794 0.53264725 0.5495169  0.61511254
  0.5498821  0.43840843 0.4449018  0.2937849  0.4596358  0.5437926
  0.58567476 0.509889   0.6390138  0.4384449  0.48692358 0.4167015
  0.5087622  0.40953708 0.5853504  0.49678785 0.49497387 0.5713384
  0.6605665  0.6260282  0.49356663 0.6180827  0.5312984  0.62432563
  0.49911416 0.6374302  0.5815333  0.51794004 0.5564835  0.6409466
  0.53315306 0.4857446  0.42565638 0.47806397 0.6625935  0.44998604
  0.5246097  0.4869281  0.49159375 0.26239562 0.5501081  0.44941837
  0.6057944  0.66560084 0.5893692  0.6551069  0.51692885 0.58095956
  0.45657888 0.6053724  0.5161048  0.5915392  0.7139064  0.6115324
  0.5706037  0.62395656 0.622617   0.469778   0.55506325 0.44601455
  0.45566297 0.67556477 0.61044097 0.40117365 0.36279798 0.5291004
  0.5258611  0.36562863 0.5905441  0.5107958  0.59566444 0.65915835
  0.5509876  0.62017155 0.56316036 0.5643804  0.58177674 0.6226448
  0.5922197  0.43981564 0.647665   0.6024318  0.243556


[[0.48611417 0.39321685 0.4899204  0.3809474  0.51897603 0.47212386
  0.53590614 0.5414039  0.5141159  0.48123616 0.4511395  0.4564733
  0.49216208 0.47332686 0.44421202 0.4209109  0.48719376 0.42053583
  0.4893449  0.4221534  0.5643275  0.51882005 0.4194792  0.43029603
  0.54932064 0.45925957 0.5353825  0.3497954  0.32852927 0.35331315
  0.43606287 0.43074375 0.46917802 0.3931424  0.41159022 0.24434848
  0.44862235 0.32911992]]



[[0.40870643 0.30308533 0.23122954 0.2868623  0.42140433 0.34908774
  0.46904132 0.41823232 0.32290208 0.43578538 0.37897688 0.42460215
  0.29196548 0.39207333 0.54286265 0.33090007 0.44180667 0.30308533
  0.3883045  0.36465913 0.42607957 0.24054517 0.32640314 0.46084526
  0.45984298 0.45829546 0.4132525  0.35898322 0.29552102 0.14014506
  0.47052616]]



[[0.33122534 0.50066197 0.4589903  0.5337732  0.45456207 0.22511554
  0.5679367  0.5233692  0.49210322 0.5636727  0.5292104  0.51241946
  0.46174064 0.4339712  0.51089597 0.49676025 0.5519226  0.3989715
  0.5565154  0.44546315 0.5905719  0.54380715 0.5620279  0.56082594
  0.50161076 0.3611585  0.42320967 0.24373119 0.18757533 0.4448733
  0.2369463  0.25526953 0.3742648  0.29211232 0.37308744 0.45079118
  0.24373119 0.18757533 0.51284814 0.18757533 0.3011748  0.2127682
  0.4209104  0.46099788 0.27543348 0.30903995 0.18757533 0.4340903
  0.54338884 0.46776015 0.18757533 0.45465207 0.408809   0.30856264
  0.36926416 0.31392413 0.24931961 0.18757533 0.36556447 0.3072848
  0.29078126 0.60637724 0.4114921  0.23874165 0.5202531  0.5793373
  0.5257255  0.4114921  0.23874165 0.45776024 0.525622   0.5155463
  0.2959241  0.4196319  0.18757533 0.43046904 0.3320142  0.46352053
  0.49209812 0.6837131  0.2643189  0.43440285 0.514373   0.28112918
  0.25349465 0.41205215 0.49430734 0.23815805 0.317295


[[0.42880425 0.3747504  0.43506983 0.44204023 0.4237256  0.43195763
  0.50352454 0.37914914 0.3854159  0.37939858 0.22791621 0.5423603
  0.4454942  0.5467022  0.5691736  0.51401776 0.40973884 0.35978502
  0.10475674 0.46908832 0.25793394 0.3150152  0.53863865 0.37382412
  0.44201276 0.36951405 0.31239533 0.45812264 0.4015515  0.49209967
  0.41059673 0.42270225 0.47923395 0.43153083 0.45917284 0.3223039
  0.23777355 0.31015217 0.29122615 0.28686076 0.41872537 0.3300513
  0.2316135  0.16887647 0.3006431  0.2403072  0.510013   0.35057294
  0.12271318 0.3733268  0.24977466 0.2483353  0.4248087  0.17525819
  0.19615589 0.18424432 0.2967756  0.3410312  0.3369163  0.44493806
  0.3812821  0.3667906  0.31419462 0.2848894  0.3404514  0.50650644
  0.28798133 0.43282768 0.52942324 0.2610541  0.39957556 0.5129905
  0.30344704 0.33161855 0.4192719  0.27555323 0.33179396 0.47128597
  0.48401222 0.36140445 0.597348   0.3327391  0.4633765  0.41589794
  0.3871066  0.37524277 0.22737457 0.35984007 0.320


[[0.19449277 0.47397852 0.5036907  0.41726553 0.31615144 0.5165001
  0.55042756 0.49118307 0.5120499  0.6330496  0.4903923  0.43516624
  0.49577844 0.39619887 0.4413036  0.41498488 0.49105364 0.4115219
  0.48844016 0.43353468 0.5249808  0.51706415 0.36173615 0.43722877
  0.51199    0.45400488 0.42783135 0.5454986  0.55056953 0.49800068
  0.39786828 0.36529335 0.4425534  0.39854187 0.4209108  0.4039845
  0.48629576 0.3992536  0.50328827 0.4612104  0.44340748 0.53504956
  0.48529744 0.47590232 0.3563184  0.4741189  0.4626273  0.4592612 ]]



[[0.20479438 0.29144716 0.29144716 0.2766154  0.29480544 0.30747652
  0.13946217 0.26908785 0.31594303 0.34140283 0.3948998  0.36306176
  0.29144716 0.29144716 0.25983247 0.16033211 0.2847714  0.22607872
  0.29074398 0.29074398 0.22409865 0.38704568 0.38264292 0.35328633
  0.42982215 0.32346475]]



[[0.46726424 0.42946196 0.4233074  0.42753148 0.5047033  0.45336777
  0.45674124 0.4327867  0.5196073  0.4110158  0.34576645 0.5598828
  0.50695753 0.32887208 0.37129757 0.45528325 0.38105822 0.42884347
  0.48368922 0.52436984 0.34519726 0.4017741  0.45283568 0.5342664
  0.4381144  0.39054275 0.46048993]]



[[0.35931757 0.4250151  0.4289599  0.30254504 0.2817705  0.4072677
  0.4095667  0.37225685 0.3793918  0.30675623 0.27747166 0.3164074
  0.25951856 0.39339834 0.28931427 0.371048   0.307296   0.3889383
  0.3834891  0.29405212 0.40821323 0.49346    0.29406977 0.45244402
  0.5118103  0.44329327 0.46892065 0.4617344 ]]



[[0.36602163 0.3263382  0.3799701  0.11850207 0.30674446 0.24627006
  0.23322916 0.2924395  0.23054843 0.375324   0.40033478 0.40051588
  0.3088454  0.3088454  0.35574555 0.25998613 0.4168913  0.2915382
  0.2915382  0.5692403  0.40098473 0.2992487  0.48221773 0.4376986
  0.24038571 0.40009016 0.48268393 0.4652127  0.28135633 0.34684062
  0.4018294  0.4235179  0.29847378 0.24641246]]


In [ ]:
test44 ="Anti-semitism is a prevailing cultural sentiment in Africa, particularly in Accra, during the period when some of Twi literature's most celebrated figures"

In [ ]:
test44 ="During the period of Twi literature's most celebrated figures,Anti-sentism is a prevailing cultural sentiment in Africa"

In [ ]:
onlyfiles[7]

'kkkk.txt'

In [ ]:
 text_embeddings44 = model.encode(test44, batch_size = 8, show_progress_bar = True)

In [ ]:
Tokenized_Stripped[18][9]

'Many people also inherit their morality from their family, community or culture – it’s rare for somebody to ‘shop around’ for the morality that most closely fits their personal beliefs.'

In [ ]:
 text_embeddings447 = model.encode(Tokenized_Stripped[0], batch_size = 8, show_progress_bar = True)

In [ ]:
cosine_similarity([text_embeddings44],text_embeddings447)

array([[0.6460258 , 0.542941  , 0.57357   , 0.51659644, 0.60146415,
        0.5151427 , 0.60243964, 0.5444093 , 0.313645  , 0.48789406,
        0.54099166, 0.5693718 , 0.4046803 , 0.6096828 , 0.4663766 ,
        0.5042845 , 0.46195516, 0.58822376, 0.4947492 , 0.52044404,
        0.61639637, 0.6158465 , 0.49733466, 0.4306336 , 0.54164743,
        0.5392591 , 0.5591616 , 0.46975523, 0.47210544, 0.45986336,
        0.64702   , 0.5857647 , 0.5785532 , 0.5086472 , 0.39113533,
        0.4229282 , 0.5356719 , 0.5565119 , 0.55062014, 0.32833898,
        0.4683092 , 0.4512902 , 0.5304565 , 0.42572704, 0.4599232 ,
        0.58744156, 0.47959214, 0.474028  , 0.4401906 , 0.49743986,
        0.615476  , 0.55799824, 0.43483567, 0.3628835 , 0.31846678,
        0.47651058, 0.4106732 , 0.5851135 , 0.515224  , 0.54072654,
        0.469741  , 0.44519365, 0.41643643, 0.5612191 , 0.5083868 ,
        0.33719984, 0.5362853 , 0.5037774 , 0.5174217 , 0.49701065,
        0.551019  , 0.4938879 , 0.40164107, 0.25

In [ ]:
np.shape(text_e)
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  sim=cosine_similarity([text_embeddings44],text_embeddings)
  print(sim)


[[0.41375697 0.16254768 0.26457453 0.2630369  0.34190774 0.2769067
  0.2804958  0.32570887 0.2508283  0.06780523 0.3069867  0.26985592
  0.18099138 0.2851633  0.13820177 0.12953156 0.2738797  0.24491711
  0.5025205  0.2868495  0.43937305 0.39200476 0.25906956 0.17595544
  0.21427746 0.22379903 0.12608165 0.22432768 0.12498797 0.22512126
  0.4054885  0.30221152 0.17776157 0.1867644  0.23640513 0.20869172
  0.08848875 0.13782087 0.07564381 0.3594215  0.41381288 0.38326633
  0.18842325 0.03699233 0.07660156 0.21741824 0.14798386 0.22225949
  0.28441986 0.09764518 0.15165658 0.17032434 0.13064854 0.17470203
  0.15088776 0.24649552 0.03097892 0.19246826 0.1252422  0.02578299
  0.19177575 0.17641214 0.22214594 0.17531888 0.19923103 0.29253462
  0.21167645 0.05933196 0.29577303 0.0954323  0.18022414 0.41523784
  0.4112635  0.32787424]]



[[0.2521674  0.39166057 0.2223255  0.2642094  0.24849999 0.10507098
  0.00406769 0.2627515  0.17477667 0.34107172 0.237831   0.20316973
  0.35857165 0.24858502 0.2623327  0.26066542 0.2458453  0.14174384
  0.3086002  0.30907452 0.19814128 0.47849387 0.45595652 0.24435505
  0.4183881  0.05076647 0.17175925 0.32128063 0.12541716 0.21103396
  0.34202468 0.06489445 0.21680562 0.03596607 0.1814827  0.07132102
  0.23253183 0.05013147 0.26134288 0.07951999 0.34366345 0.2197249
  0.15891194 0.20121273 0.25317514 0.28818002 0.27688226 0.32304335
  0.46994624 0.37078446 0.08492334 0.08954552 0.15222076 0.13431743
  0.08204672 0.08346222 0.18631655 0.3545209  0.2750664  0.3066228
  0.22934149 0.37067068 0.14329034 0.29235044 0.04407389 0.25300324
  0.40611577 0.29667914 0.24944696 0.31936353 0.24897215 0.30393606
  0.28449577 0.31590676 0.41816023 0.36884642 0.44042397 0.15156284
  0.4261651  0.20307118 0.2634787  0.47071505 0.08586937 0.2956319
  0.23378497 0.32036    0.22376144 0.28869838 0.27


[[0.22169667 0.2724563  0.33791825 0.13957047 0.35854524 0.41235098
  0.36345518 0.33066466 0.16554122 0.24905771 0.20486729 0.16642727
  0.29953492 0.31459826 0.19537231 0.29196632 0.39077997 0.35284913
  0.17662236 0.2901258  0.29198152 0.250055   0.16641134 0.58845884
  0.26561326 0.3678378  0.42121458 0.2746279  0.3969249  0.5305589
  0.10202684 0.2966118  0.432925   0.28971902 0.398992   0.35863185
  0.19840151 0.17191233 0.28658104 0.16861334 0.19144027 0.10832496
  0.1855646  0.28140876 0.32049838 0.2116406  0.28855994 0.14003943
  0.35357726 0.2551415  0.2954357  0.356527   0.22779515 0.26095644
  0.40309364 0.21347672 0.28377593 0.21317188 0.30481666 0.27687404
  0.24442114 0.35595638 0.48343086 0.27567783 0.22085366 0.1309284
  0.19948103 0.2260943  0.20794764 0.18641087 0.03405549 0.17655799
  0.10750758 0.29687697 0.13512559 0.07271929 0.10361339 0.4347987
  0.5263119  0.24338925 0.26661253 0.3147386  0.21079671 0.4396893
  0.10194623 0.41394007 0.07851394 0.16402256 0.337


[[0.3306491  0.03549259 0.2605809  ... 0.42512336 0.43593663 0.45362866]]



[[0.21720654 0.26969117 0.02174132 0.11516141 0.15516582 0.22998185
  0.41946733 0.18509328 0.26995432 0.2430515  0.30380058 0.00590278
  0.11643129 0.16590603 0.3010503  0.28275412 0.27478194 0.14041439
  0.24562386 0.24873379 0.21971184 0.17120078 0.21081936 0.12581547
  0.28541243 0.33059108 0.1856574  0.32764757 0.17742833 0.3322748
  0.18932071 0.22621116 0.3072664  0.25617194 0.17052996 0.20722932
  0.20916803 0.13719839 0.18878919 0.12783353 0.27245945 0.3540765
  0.2984862  0.3104763  0.2592207  0.17991227 0.10955513 0.22897516
  0.24828398 0.25231487 0.21494766 0.22206436 0.17099586 0.24334481
  0.19446534 0.19701461 0.19266205 0.0546015  0.11214349 0.14907593
  0.19289972 0.22967122 0.18447661 0.20076676 0.27234122 0.2487932
  0.26884228 0.1693056  0.2383545  0.25471014 0.23905696 0.2806112
  0.18585685 0.28376317 0.3343581  0.32777786 0.31961793 0.27331692
  0.25006863 0.27194977 0.38392523 0.29581714 0.21276872 0.29819146
  0.3612907  0.27958465 0.31037027 0.37821954 0.332


[[0.363852   0.29119247]]



[[0.33965558 0.12617403 0.32742462 0.26431015 0.26351735 0.34099716
  0.2922356  0.20456383 0.15814088 0.3385762  0.36391008 0.26861858
  0.28113395 0.12621748 0.17486513 0.15487976 0.28064185 0.3125369
  0.11677219 0.38495666 0.30350804 0.36391008 0.34186465 0.32535324
  0.22393024 0.42342356 0.27722532 0.3317717  0.22393472 0.11797817
  0.37486464 0.25609478 0.37094742 0.3578369  0.11936416 0.34443766
  0.31941003 0.20973149 0.21921828 0.33022943 0.286684   0.4100132
  0.25645372 0.31660908 0.45699784 0.34483466 0.3240534  0.27352205
  0.37422612 0.25371552 0.27195546 0.24521181 0.31705573 0.28936583
  0.28936583 0.29315197 0.44901305 0.21020028 0.28954762 0.28654385
  0.37096053 0.30262357 0.46255308 0.41251612 0.38674116 0.29916072
  0.3205547  0.35232943 0.31819737 0.34864762 0.18463579 0.3197114
  0.30309343 0.37385148 0.3413412  0.3124839  0.38278687 0.3616896
  0.18878932 0.2966609  0.31903434 0.25031328 0.33836743 0.30691803
  0.30755082 0.4368343  0.32101524 0.28921312 0.293

KeyboardInterrupt: ignored

In [ ]:
tes_embed = model.encode(test, batch_size = 8, show_progress_bar = True)
np.shape(tes_embed)
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  if len(tes_embed)>len(text_embeddings):
    length = len(text_embeddings)
  else:
    length = len(tes_embed)
  for k in range(length):
    for t in range(len(text_embeddings)):
      simi = cosine_similarity(tes_embed[k].reshape(1,-1),text_embeddings[k][t].reshape(1,-1))
      sumed = simi+sumed
  print(sumed/len(text_embeddings))



[[1.4324324]]



[[-0.25114155]]



[[-0.6862745]]


IndexError: ignored

In [ ]:
print(len(database))

582049


In [ ]:
print(main_embeddings)

[-6.61817670e-01  6.38987362e-01 -1.02570966e-01 -3.73195767e-01
 -4.34944808e-01 -3.52733284e-01  9.97304440e-01  8.20522159e-02
  8.03084135e-01 -4.16949868e-01  3.71349789e-02  3.15745056e-01
  3.04366678e-01  7.50192165e-01  2.39483148e-01  7.85289347e-01
 -3.14035147e-01 -2.47638583e-01 -1.48447260e-01 -9.38316528e-03
  1.50412381e-01 -1.78609602e-02  5.47908664e-01  7.18791783e-01
  1.05078959e+00  4.32738960e-01  3.96034479e-01 -4.02998060e-01
 -1.22243190e+00  5.24881966e-02 -1.81545317e-01 -2.69827731e-02
 -6.36421680e-01 -2.10296944e-01 -9.49822962e-02  8.37351322e-01
 -9.14114490e-02  3.41308653e-01  2.04034805e-01 -3.92201990e-02
 -2.15424269e-01 -3.64960581e-01  6.64936662e-01  5.66494986e-02
 -1.28374743e+00 -6.47607148e-01 -4.37002718e-01  1.14854217e+00
  7.75625348e-01 -3.81231755e-01  3.81508142e-01  6.80914521e-01
  1.04670048e+00  4.85473782e-01 -3.77297968e-01  2.68739998e-01
 -2.50346094e-01 -1.20054793e+00 -1.65917784e-01 -1.26058328e+00
  2.39253104e-01  6.73994

In [ ]:
databasedict ={}

#Trial user 1

In [ ]:
textCit = read_file("/content/Project_info/citation.txt")
sentencesCit=sent_tokenize(textCit)

In [ ]:
text_embedCit = model.encode(textCit, batch_size = 8, show_progress_bar = True)

In [ ]:
np.shape(Atten_embeddings2)
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  if len(Atten_embeddings2)>len(text_embeddings):
    length = len(text_embeddings)
  else:
    length = len(Atten_embeddings2)
  for k in range(length):
    simi = cosine_similarity(Atten_embeddings2[k].reshape(1, -1),text_embeddings[k].reshape(1, -1))
    sumed = simi+sumed
  print((sumed/length)*100)


[[30.484222]]



[[43.372646]]



[[36.28237]]



[[37.37336]]



[[40.878452]]



[[38.320244]]



[[39.71659]]



[[41.741974]]



[[36.14677]]



[[32.702488]]



[[100.]]



[[39.33419]]


In [ ]:
test="Recurrent Neural Networks (RNNs) have long been the dominant architecture in sequence-to-sequence learning. RNNs, however, are inherently sequential models that do not allow parallelization of their computations. Transformers are emerging as a natural alternative to standard RNNs, replacing recurrent computations with a multi-head attention mechanism. In this paper, we propose the SepFormer, a novel RNN-free"

In [ ]:
print(tes_embed)

NameError: ignored

In [ ]:
tes_embed = model.encode(test, batch_size = 8, show_progress_bar = True)
np.shape(tes_embed)
#thislength=3
for i in range(len(Tokenized_Stripped)):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  if len(tes_embed)>len(text_embeddings):
    length = len(text_embeddings)
  else:
    length = len(tes_embed)
  for k in range(length):
    for t in range(len(text_embeddings)):
      simi = cosine_similarity(tes_embed[k].reshape(1,-1),text_embeddings[k][t].reshape(1,-1))
      sumed = simi+sumed
  print(sumed/len(text_embeddings))




[[-0.8466077]]



[[0.06122449]]



[[-0.12544803]]



[[0.47368422]]



[[1.4285715]]



[[0.20833333]]


IndexError: ignored

In [ ]:
tes_embed = model.encode(test, batch_size = 8, show_progress_bar = True)

In [ ]:
np.shape(tes_embed)

(768,)

In [ ]:
print(tes_embed)

[-1.90909475e-01  2.86347687e-01  7.55041242e-01  1.10606469e-01
 -1.06006309e-01 -1.03744256e+00  1.14681244e+00  1.56690910e-01
  5.99125445e-01  1.36836618e-01 -6.34208247e-02  1.07847738e+00
 -2.63955057e-01  5.20655155e-01 -7.51057625e-01  2.35116050e-01
  2.11993322e-01 -7.10316122e-01  2.87952691e-01 -1.84008121e-01
 -4.29432392e-01 -2.83404678e-01 -3.66143882e-01  7.04268813e-01
  6.35808527e-01  1.48651108e-01  2.84102321e-01 -7.10724294e-01
 -5.55356383e-01  5.68372369e-01 -9.96455848e-02  6.64317846e-01
  1.86105311e-01 -1.77283794e-01  2.72280306e-01  1.02039516e+00
  4.96231169e-01  8.61874372e-02  1.14951104e-01  1.77068502e-01
  7.16786146e-01 -2.98934102e-01 -2.80096810e-02 -2.35481620e-01
 -1.04228187e+00  9.29936320e-02  3.83016691e-02  4.44195360e-01
  1.77863836e-01 -8.95455897e-01 -1.37124896e+00  4.81803507e-01
  6.06530547e-01  8.57123807e-02 -3.19107264e-01 -6.00900888e-01
  7.84898818e-01 -1.42043948e+00 -2.02225484e-02 -1.10778379e+00
 -9.05163527e-01  2.85018

In [ ]:
np.shape(main_embeddings)

(768,)

In [ ]:
np.shape(main_embeddings)
#thislength=3
#for i in range(len(Tokenized_Stripped)):
 # text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
 # np.shape(text_embeddings)
sumed =0
length = len(tes_embed)
  for k in range(length):
    for t in range(len(text_embeddings)):
      simi = cosine_similarity(tes_embed[k].reshape(1,-1),text_embeddings[k][t].reshape(1,-1))
      sumed = simi+sumed
  print(sumed/len(text_embeddings))

KeyboardInterrupt: ignored

In [ ]:
print(sumed)

[[10.]]


In [ ]:
for t in range(len(text_embeddings)):
      simi = cosine_similarity(tes_embed[k].reshape(1,-1),text_embeddings[k][t].reshape(1,-1))
sumed = simi+sumed

In [ ]:
print(sumed)

[[1.]]


In [ ]:
print(text_embeddings[k].reshape(1, -1))

[[-2.17647254e-01  6.35728776e-01  4.63638961e-01  1.83157206e-01
   9.29833502e-02 -1.09662533e+00  1.88871264e-01  7.73869932e-01
   5.39951086e-01 -6.65277898e-01  5.95942795e-01  4.98301595e-01
   6.68760717e-01  1.63072824e-01 -2.88751811e-01  5.28785884e-01
  -3.62662137e-01 -2.21896470e-01  3.54223698e-01 -3.64885122e-01
  -4.93986130e-01 -6.47365272e-01  2.92527616e-01  8.38081777e-01
   1.11425996e+00  8.06962192e-01  2.25735396e-01 -8.43836188e-01
  -4.19089675e-01  3.50038737e-01 -4.39638257e-01  3.03118527e-01
  -4.21430208e-02 -4.12565082e-01  8.03538620e-01  9.08600926e-01
   5.81256211e-01  3.73905212e-01 -4.50405896e-01 -3.78674679e-02
   5.73290288e-01 -1.21008384e+00  1.80170670e-01 -2.91935831e-01
  -1.15487313e+00  9.86033604e-02 -8.18603039e-01  1.24152815e+00
   2.12699816e-01 -8.54278564e-01 -1.39713967e+00  6.43336833e-01
   2.11666569e-01 -1.74023196e-01 -3.36562008e-01 -5.57838939e-02
   5.54626524e-01 -7.71933198e-01 -7.30764940e-02 -8.41407180e-01
  -5.96127

In [ ]:
tes_embed = model.encode(test, batch_size = 8, show_progress_bar = True)
np.shape(tes_embed)
#thislength=3
for i in range(len(Tokenized_Stripped)-5):
  text_embeddings = model.encode(Tokenized_Stripped[i], batch_size = 8, show_progress_bar = True)
  np.shape(text_embeddings)
  sumed =0
  if len(Atten_embeddings2)>len(text_embeddings):
    length = len(text_embeddings)
  else:
    length = len(Atten_embeddings2)
  for k in range(length):
    for t in range(len(text_embeddings)):
      simi = cosine_similarity(tes_embed[k].reshape(1,-1),text_embeddings[k][t].reshape(1,-1))
      sumed = simi+sumed
  print(sumed/len(text_embeddings))




[[-0.7463127]]



[[0.06122449]]



[[-0.48387095]]



[[0.47368422]]



[[1.4285715]]



[[0.20833333]]


IndexError: ignored